### ISSUE TITLE
show should parenthesize negative integers

### ISSUE THREAD

**Issue by no-longer-on-githu-b** [purescript/purescript-prelude#127]
`show (-1) == "-1"`, but should be `show (-1) == "(-1)"`.

**Comment by hdgarrood** [comment]
In general, I'm not a fan of the idea that Show instances should produce executable code that can be run to produce the same thing, because I think it's more useful to aim to have an instance which displays information which is as easy as possible to understand in the repl, and these two principles are often in opposition.

Regarding this specific suggestion, I'm not keen - I prefer the current instance. I'm also not able to come up with a concrete example where this suggested instance is an improvement.

**Comment by paf31** [comment]
> and these two principles are often in opposition.

There is an interesting compromise in the `pretty-show` haskell library, which turns "law"-abiding `Show` instances into pretty printers.

**Comment by garyb** [comment]
I'll close this for now. I guess maybe with #46 we'd insert parens as necessary here, but it's not come up again since so doesn't seem to be particularly high priority.
