### ISSUE TITLE
Int Not an EuclideanRing

### ISSUE THREAD

**Issue by eric-corumdigital** [purescript/purescript-prelude#204]
Integral domain: `one /= zero`, and if `a` and `b` are both nonzero then so is their product `a * b`

Counterexamples:
1. `-2147483648 * 2 = 0`
2. `2147483647 * 2147483647 = 0`

**Comment by hdgarrood** [comment]
Yeah, these are unfortunate. This is a law failure I can live with though, similarly to how `Number` fails to satisfy most of the laws of the numeric hierarchy.

**Comment by eric-corumdigital** [comment]
A strength of PureScript's Prelude is the sophisticated numeric class hierarchy. To me, it is counterproductive to then willfully violate it.

The existence of unlawful Number instances should not justify the existence of other unlawful instances. Each instance should have its own independent justification.

I am trying to be particular about the code I write, and I have a reliance on types actually being Euclidean rings and not sort-of Euclidean rings. The existence of the Int instance is a way in which what I am otherwise am doing right can be wrong.

The question that arises then is: how does one obtain quotients and remainders? One option is to have monomorphic definitions for Int.

**Comment by hdgarrood** [comment]
I agree that each instance should have its own justification, but the justification happens to be the same in these cases: `Int` and `Number` are approximations to the integers and the rationals respectively, and you have to be aware of where the approximation breaks down when you're using them. In any case, people need to write code which performs arithmetical operations on these types; not providing these instances is just going to make writing this sort of code less convenient, and not really any safer.

You obtain quotients and remainders on `Int` using `/` and `mod` (or the monomorphic `quot` and `rem` if you prefer flooring division). If you are likely to end up with a integers near +- 2^31, the maximum of what `Int` allows, you should not be using `Int`; use `BigInt` or something else instead. I don't know if rings of the form Z/nZ where n is a power of 2 are going to be Euclidean in general.

**Comment by hdgarrood** [comment]
> I don't know if rings of the form Z/nZ where n is a power of 2 are going to be Euclidean in general.

Thought about this a little more and the answer is fairly straightforward actually: rings of the form Z/nZ, where n = 2^m, will never be integral domains for m >= 2, because 2 * 2^(m-1) = 0. If you need a fully law abiding Euclidean ring you will just have to use `BigInt`.

**Comment by eric-corumdigital** [comment]
I disagree that Int should be an approximation of the integers. There is ample utility in Int while acknowledging that it is, in fact, bounded. On the other hand, I am not convinced there is significant utility in treating Int as the integers. Where that is required, as you acknowledged, we already have BigInt.

If there is no EuclideanRing instance for Int, then is Int less convenient? Probably so. By a lot? Well, I already have to import extra definitions to deal with Ints and Numbers and conversions between, and codecs, so I am not sure that in practicality the difference is significant. As you acknowledged, there are already special `quot` and `rem` definitions for Int.

If I could semantically search for uses of `/` and `mod` for `Int`, I would, and that would give an idea of how significant this instance actually is.

**Comment by hdgarrood** [comment]
It's strange to me to argue that Int is not used as an approximation of the integers. In my experience, 99% of the time, I'm thinking "this value should be an integer, I'll use Int", not "this value should be a member of Z/2^32Z, I'll use Int". I feel like I use `/` for `Int` quite often, too. Sorry, but I'm going to close this.

**Comment by bagrounds** [comment]
> `Int` and `Number` are approximations to the integers and the rationals respectively, and you have to be aware of where the approximation breaks down when you're using them.

This argument seems out of place in a language designed around type safety.

Consider this analogous argument:

Functions that throw exceptions are approximations of functions, and you have to be aware of where the approximation breaks down when you're using them.

But PureScript does not allow functions to throw exceptions (without plumbing a Partial constraint through the call stack).
This added type safety gives us more guarantees about program correctness, which provides great tangible benefits during development.
I don't see why the same rationale shouldn't apply for 32 bit `Int`s.

I choose PureScript over JavaScript because I recognize that, for all but the most trivial programs, my human brain cannot maintain awareness of the boundaries of all of these approximations. Luckily I don't have to. The compiler does that for me.

> In any case, people need to write code which performs arithmetical operations on these types; not providing these instances is just going to make writing this sort of code less convenient, and not really any safer.

Perhaps it would be useful to split the discussion into two independent questions.

First, should `Int` obey the laws assumed by the type class instances that it implements?
In general, should types obey the laws assumed by the type class instances they implement?

To me, it seems obvious that they should. Why have laws at all if we're just going to break them? But I'm sure there's room for further debate on that question.

After answering that questions, we could consider the other questions around practicality and convenience.

32 bit `Int`s do not have the EuclideanRing type class instance, but it's common for programmers to do arithmetic, including division, with 32 bit `Int`s. How can we make 32 bit `Int` division convenient without breaking any laws?

A couple of candidate solutions for the practicality question readily come to mind.

* Export the `/` operator for 32 bit `Int`s, but not as a member of the EuclideanRing type class. Programmers can solve the namespace issues with the typical strategies used for any two functions that happen to have the same name.
* Export a similar operator. For example, `~/` looks kind of like "approximate division", and it's immediately clear that it is not regular, law abiding division. It's not much more typing, either.

Note: I came across this issue, not because I wanted a law abiding EuclideanRing instance for `Int`, but because I was looking for a `BoundedEnum` instance for `Int`. Strangely, `Int` seems to abide by the `BoundedEnum` laws, but does not have an instance. Maybe I should open a separate issue for this.

**Comment by hdgarrood** [comment]
The same rationale does not apply because there is an issue of diminishing returns when trying to make everything behave impeccably. In practice it’s very rare to run into these limitations, and for 99% of cases the best choice is in fact to use the same number types that everyone else does, because they are significantly faster, have better memory usage, and can interoperate with the rest of the target language ecosystem. It wouldn’t be a good tradeoff to make it more awkward to work with the number types that you really should be using in the vast majority of cases for the sake of a pitfall that almost all programmers are already aware of anyway.

**Comment by hdgarrood** [comment]
I still think the design we have right now, where Int and Number have non-law-abiding numeric hierarchy instances, is the right one, but speaking more practically, removing the unlawful instances is just not a possibility at this stage, as it would break the vast majority of code that works with Int and Number for a benefit that seems to appeal only to a fairly small minority of the community (sorry). Removing these instances would seriously piss off a lot of users, and it would be hard to fault them.

**Comment by JordanMartinez** [comment]
> I choose PureScript over JavaScript because I recognize that, for all but the most trivial programs, my human brain cannot maintain awareness of the boundaries of all of these approximations. Luckily I don't have to. The compiler does that for me.

Couldn't you define a newtype over `Int` and `Number` that doesn't have a `EuclideanRing` instance? Then you don't have to worry about possibly misusing it without angering the majority users who want to use `/`. Any concerns about performance issues are resolved using zero-cost `coerce` since `v0.14.0`.

**Comment by hdgarrood** [comment]
I think my recommendation if you want to work around this in your own projects would be to define your own Prelude with a parallel set of type classes with the same members, and to avoid giving instances to types where they wouldn’t be law abiding.

**Comment by JordanMartinez** [comment]
Ah... That is a better solution...
