### ISSUE TITLE
Record instances

### ISSUE THREAD

**Issue by kl0tl** [purescript/purescript-prelude#207]
Are `Semigroup`, `Monoid`, `Semiring` and `Ring` instances for records using `Record.Unsafe.unsafeSet` on purpose instead of composing a bunch of record builders? Don’t that yield a lot more garbage?

Also is there a reason for not having records instances of `Bounded`, `EuclideanRing` and `DivisionRing`?

**Comment by natefaubion** [comment]
Not necessarily more garbage since builders will allocate closures (as opposed to new records). I think it's mainly that `prelude` doesn't depend on any other libraries, and `Builder` is part of `purescript-record`.

**Comment by hdgarrood** [comment]
There is a reason for not including EuclideanRing and DivisionRing: there’s no clear way of defining division when you have more than one field in the record. What should `{ a:1, b:2, c:3 } / { a:4, b:5, c:6 }` be? Note that we can’t do `{ a: 1/4, b: 2/5; c: 3/6 }` because that won’t satisfy the laws. In particular, division needs to be defined for any nonzero divisor, but if you have a zero in at least one field (but not all fields) you have an undefined result.

**Comment by hdgarrood** [comment]
I think a Bounded instance makes sense, given that we already give records Ord instances.

**Comment by kl0tl** [comment]
Thank you both for your answers 🙇 I added a `Bounded` instance for records in https://github.com/purescript/purescript-prelude/pull/208.
