### ISSUE TITLE
[generics-rep] newtype NoConstructors = NoConstructors Void

### ISSUE THREAD

**Issue by no-longer-on-githu-b** [purescript/purescript-prelude#247]
This way you can use `absurd`. Although if we implement https://github.com/purescript/purescript/issues/2922 then this is not necessary.

**Comment by JordanMartinez** [comment]
I'm going to close this for the time being. I don't think this is relevant until the above issue is implemented (if we do decide to do that).

**Comment by hdgarrood** [comment]
I think it is still relevant, because regardless of what we do in the linked issue, we should provide a way of eliminating a NoConstructors value so that users don’t need to resort to unsafe functions. It does depend on the result of that issue but if we don’t do anything there then we will need to do something here.

**Comment by hdgarrood** [comment]
(It’s not vital to address this before 0.14 but that doesn’t mean it can’t stay open.)

**Comment by JordanMartinez** [comment]
Makes sense. I feel like this should have a label on it indicating that it depends on the compiler so that one doesn't have to read the whole thing to understand that and so we can filter it out of searches.
