### ISSUE TITLE
Consider adding `ShowAtom` class for better parenthesising

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-prelude#34]
See https://github.com/paf31/purescript-nonempty/pull/3#discussion_r35231989

**Comment by paf31** [comment]
We could also make a `purescript-sexpr` library, which would support the equivalents of `show` and (a fairly efficient) `read`.

**Comment by hdgarrood** [comment]
I think the goals of seeing what's going on in a repl or debugging (that is, what I understand `Show` to be for) and serialization for passing data across various boundaries are separate. We already have at least two options for serialization using JSON, so I would vote that we keep `Show` simple (that is, just for inspecting values in the repl). I like the `ShowAtom` design.

**Comment by LiamGoodacre** [comment]
Should this be closed now `purescript-sexpr` exists?

**Comment by paf31** [comment]
I don't think so, it solves a slightly different problem.

**Comment by no-longer-on-githu-b** [comment]
purescript-sexp is more a general serialization library. And its output for generics isn't particularly readable:

    ("SProd" "NN.Vertex.Vertex" ("SString" "") ("SProd" "Data.List.Types.Cons" ("SProd" "NN.Vertex.VertexID" ("SString" "f078fc05-c9c0-4c9b-9c09-12b026e05c60")) ("SProd" "Data.List.Types.Nil")) ("SProd" "NN.Vertex.Style.Normal"))

I think the best way to solve all the `Show` formatting issues would be to make the `show` method return a PureScript expression AST instead of a string, and provide a function that turns an AST into a string. This would also prevent people from abusing `Show` for any old to-string behavior (for display instead of debug). But that would burden purescript-prelude quite a lot.

**Comment by garyb** [comment]
I guess we'll probably be doing #46 instead, when default member implementations is a thing.
