### ISSUE TITLE
Use `showsPrec`.

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-prelude#46]
If we want to derive `Show`, we should change `show` to `showsPrec`.

**Comment by paf31** [comment]
It seems the core libraries now use the "sexpr-style" `Show` instances:

``` purescript
> show $ Tuple 1 true
"(Tuple 1 true)"

> show $ Just "testing"
"(Just \"testing\")"
```

so maybe we don't need `showsPrec` after all? If we're willing to accept a possibly redundant set of parens on the outermost type constructor, we'll always get an evaluable string of text this way, I think.

We could instead change the documentation, core libraries and `gShow` function to use this sexpr-style approach everywhere.

**Comment by JordanMartinez** [comment]
Should this be closed?

**Comment by hdgarrood** [comment]
I think possibly-redundant parens in Show instances is still not ideal. However, if we want to do something about this, then I think instead of `showsPrec`, it may be best done by replacing Show entirely with something like https://github.com/hdgarrood/purescript-debugged. If we are closing this, then perhaps we should create a new issue for that instead.

**Comment by JordanMartinez** [comment]
I would love to transition from `Show` to `Debugged`!
