### ISSUE TITLE
`not` should be spelled consistently with (&&) and (||)

### ISSUE THREAD

**Issue by chrisdotcode** [purescript/purescript-prelude#49]
Personally, I prefer just using `and`, `or`, and `not`, which are far more aesthetically pleasing aliases for `conj` and `disj` and `not` than `&&`, `||` and `!`, but either way, as of now - the naming schema is not consistent: two are symbol-names and one is alphanum.

**Comment by garyb** [comment]
Actually they're all named: `conj`, `disj`, and `not`. `(&&)` and (||)`are aliases for`conj`and`disj`.

https://github.com/purescript/purescript-prelude/blob/5b8da18fd7b8d57a85df49ec64099a81b13f42f7/src/Prelude.purs#L797-L800

**Comment by chrisdotcode** [comment]
Mhm. I adjusted my comment above to reflect that. What do you think of aliases in the form of `and`, and `or`, to be consistent with `not` - or introducing a `!`.

**Comment by hdgarrood** [comment]
I'm not keen, there's no precedence for `!` meaning `not` in ML family languages, as far as I know, and adding a special case for `!` to the language syntax (which we'd need to do to implement this) stops you from using `!` in an operator section, which is currently possible:

``` purescript
> let (!) = Data.Array.Unsafe.unsafeIndex
> map (! 0) [[1], [2]]
[1,2]
```

(Come to think of it, in light of this, I'm less keen on the only unary operator special case that we do have, namely `-`, which gets desugared to `negate`)

**Comment by garyb** [comment]
I'm not sure we have a good reason to use `conj` and `disj` anymore actually. They were named that way originally as they were lattice operators (and `meet` and `join` were less than ideal due to `join` overlapping with monad `join`), but we did away with the lattice hierarchy in the end.

I'd be fine with naming them `and` and `or`.

I'm also not a fan of introducing a unary boolean negation, the numeric `negate` is nasty enough as it is, but without it we can't write negative numbers natually, so it's just about worth it there.

**Comment by hdgarrood** [comment]
There's also the conflict with `Data.Foldable`, which already exports an `and` and an `or`.

**Comment by garyb** [comment]
Ah right, good point.

**Comment by hdgarrood** [comment]
In my mind, `conj` and `disj` are boolean algebra words anyway, not just for lattices. Wikipedia seems to agree (but then again, I got most of my information about boolean algebras from that page, so yay circular reasoning).

**Comment by garyb** [comment]
Oh, they definitely are, just they're not as familiar as `and` and `or` I guess.

**Comment by hdgarrood** [comment]
Ah, I see, yeah. I also think `conj` and `disj` suggest a generalization from booleans to boolean algebras, whereas `and` and `or` don't to the same extent? But I guess you could use that to argue that `and` and `or` from `Data.Foldable` could be changed, too, and I don't think I'd go that far.

**Comment by chrisdotcode** [comment]
So, then, since it seems that's decided, how about adding (!) for consistency in the other direction?

**Comment by hdgarrood** [comment]
Sorry, I don't follow. What other direction?

**Comment by chrisdotcode** [comment]
So, consistency is one direction is having `&&` and `||` have alphanumeric function names.

Consistency in the other direction is having `not` having a symbolic name, id est `!`.

**Comment by hdgarrood** [comment]
I mean, yeah, if you look at it that way, it's inconsistent. But I'm not convinced that it's such a good way of looking at it. There already is a rule which is pretty consistently applied, in my view: If a function is binary, and would benefit from having an operator alias, and we can think of a good one, then it gets one.

Would you say the following is a fair representation of your argument?
- `(&&)`, `(||)`, and `not` all have something in common, that is, that they are basic boolean (algebra) operations.
- Because they all have this in common, then, for consistency, either all of them should also have symbolic operators, or none of them should.

You can come up with thousands of other properties that PureScript values might or might not have, and therefore, thousands of other ways of choosing a particular set and saying that everything in this set should be consistent in some way. And there's nothing in this argument that sets your chosen property - namely, being a boolean algebra operation - apart from other properties.

However, there is something that sets binary functions apart from other values. That is, the way the language syntax works means that operators are not really suitable for anything other than binary functions. So I think the current approach of giving `conj` and `disj` operators, but not `not`, is well justified.

**Comment by chrisdotcode** [comment]
Yes, you've got my argument correct.

So basically, you're saying that since `not` is unary, it's less similar to `&&` and `||` than I had initially said? That makes sense.

`not`, is however different from other operators in general - it's `!` in other languages. Homogeneity with Grandpa JavaScript was also one of the reasons I'm thinking about.

**Comment by hdgarrood** [comment]
Cool. Yes, I think that's a good summary of my point.

I still think the syntax issue trumps familiarity, personally.

**Comment by chrisdotcode** [comment]
Well, that's as far as my opinion takes me. If the higher-ups are against, feel free to close.

**Comment by hdgarrood** [comment]
Close this? I think the current situation is fine, and anyway, there doesn't seem to be any good way of defining unary operators with the current language syntax.

**Comment by garyb** [comment]
If we're going to break stuff I'd perhaps be in favour of using `and` and `or` and coming up with something else for the `Foldable` functions. Thoughts anyone?

**Comment by paf31** [comment]
I don't see any reason to break this, honestly.

**Comment by tfausak** [comment]
I prefer `and` and `or` to `conj` and `disj`. I am fine with saying `all id` for `Data.Foldable.and` and `any id` for `Data.Foldable.or`.

**Comment by hdgarrood** [comment]
I think the way things currently are is ideal: I think the best (or at least, most natural) notation for conjunction and disjunction is infix, and so operators are better suited than `and` or `or`. I also like having `and` and `or` in `Data.Foldable`.

Firm :-1: for any of the suggested changes in this thread from me, sorry.

**Comment by chrisdotcode** [comment]
Alright, I'll close this, then.
