### ISSUE TITLE
More documentation for EuclideanRing

### ISSUE THREAD

**Issue by clayrat** [purescript/purescript-prelude#99]
Is there any practical use to the `degree` function? One could probably use it to write a law test for `div` and `mod`, but beyond that?

**Comment by garyb** [comment]
There probably are some uses that I'm unaware of, but it's primarily there so we have a way of talking about the laws for `div` and `mod`. Also it's part of the definition of what a Euclidean ring is, so dropping it from the class would be odd in that regard, if we name it as such.

We adopted `EuclideanRing` over the old `ModuloSemiring` to have a good way of expressing the fact that division by zero is undefined, since the `div` behaviour is only specified when `degree a > 0` and `degree a <= degree (a * b)`. We could have added some law(s) to the old `ModuloSemiring`, but that whole thing was pretty ad-hoc already, whereas at least now we're formulated in terms of a structure that has previously been studied!

Having it just because it's necessary for the laws is good enough reason to have it anyway, IMO!

**Comment by clayrat** [comment]
I see. Might be worth adding this explanation in some form as a comment to the code!

**Comment by hdgarrood** [comment]
Reading this, looking at the laws for `EuclideanRing` again, and comparing it to the definition of a euclidean domain, I'm a bit confused. My most important question is, do we agree with the definition given in https://en.wikipedia.org/wiki/Euclidean_domain, and is this what we're aiming to capture with the `EuclideanRing` class?

If the answer to the above is yes, then:
- How did we end up with this formulation of `EuclideanRing`? It looks a bit different from what I would have expected, given the Wikipedia definition. For example, I would have expected to see something like: "for any `a` and any `b` not equal to 0,  let `q = a / b`, and `r = a `mod` b`. Then `a = q*b + r`, and either `r == 0` or `degree r < degree b`". Or perhaps a slightly more sensible formulation would be to replace "either `r == 0` or `degree r < degree b`" with just "`degree r < degree b`", since the Wikipedia definition says that a Euclidean function does not actually have to be defined at 0, but in our case it's probably easier to have `degree` just take any `a` (including `zero :: a`), and probably we want `degree zero == 0`.
- If we are trying to deal with division by zero by saying that the `div`/`mod` behaviour is only specified when `degree a > 0` and `degree a <= degree (a*b)`, doesn't that admit a law-abiding (but wrong) instance for any `CommutativeRing` in which we have `degree = const 0`, and then we are free to do literally anything with `div` and `mod`?
- We have a law named 'multiplicative euclidean function', but this doesn't seem to match with what Wikipedia says, which is that a multiplicative euclidean function is one where f(ab) = f(a) \* f(b). Perhaps we just want `degree` to be submultiplicative? (Full multiplicativity is stronger than what we require or even want, as far as I can tell; according to this question it is unknown whether all euclidean domains admit multiplicative euclidean functions! -- http://math.stackexchange.com/questions/274606/multiplicative-euclidean-function-for-an-euclidean-domain) _edit:_ By "submultiplicativity" I just mean that `degree a <= degree (a * b)` for all `a` and `b`, provided that both `a /= 0` and `b /= 0`.
- Should there be a law requiring that `degree x` is always nonnegative?

**Comment by hdgarrood** [comment]
Note to self for later: I found this rather useful: http://journals.tubitak.gov.tr/math/issues/mat-95-19-3/pp-291-299.pdf (found via here: http://mathoverflow.net/questions/31681/euclidean-function-at-0) which discusses some of the finer points around the implications of different choices for how `degree zero` should behave in the definition. I'm now leaning towards leaving it undefined, just like division by zero.

**Comment by hdgarrood** [comment]
@clayrat: I suppose I might have closed this a little prematurely. Having done a bit more reading, I'm more confident I understand this class. In short, the laws regarding `degree` ensure that `gcd` (which is new in v2.3.0) always terminates, because the remainders are always getting smaller after repeated applications of `mod`; that's the main reason it's there.

The class could still work without an actual member `degree` but I think it's a good thing that you have to write it out - both from a documentation perspective and because being forced to write it might make you realise you don't actually have a valid instance.

The most obvious application I can think of is for testing laws automatically using @garyb's purescript-quickcheck-laws. Another application is for polynomials over a field, which form a Euclidean ring, where the `degree` function is actually the degree of the polynomial, i.e. the highest power of x appearing. It's a little harder to think of a concrete use case for polynomials, admittedly.

Does that answer your question? I agree that this should go somewhere a bit more obvious like in the class - in fact I think I'm going to reopen this as a reminder to document EuclideanRing a bit more thoroughly. I'm very happy to explain further if you have any other questions. There's also a very relevant discussion in #106.

**Comment by rgrempel** [comment]
I'm looking at https://github.com/rgrempel/purescript-int-53/issues/7, and in that context I'm wondering why `degree` is defined as `a -> Int` rather than `a -> a`?

My practical problem is that `Int53` is larger than `Int`, and the appropriate implementation for `degree` is `abs`. But, of course, my `abs` produces an `Int53` rather than an `Int`.

Of course, I could truncate, but that doesn't seem quite right either.

**Comment by hdgarrood** [comment]
The codomain of `degree` doesn't necessarily have to be `Int`, but it should be a well-ordered set (that is, a totally ordered set where every subset has a unique least element).

Of course, these are the sorts of ideas that start to get a bit fuzzy in the discrete world of computers; you could well argue that the set of `Number` values is such a set, for instance, even though the set they're supposed to represent, the reals, isn't well-ordered. But even so I don't think `a -> a` would be a better choice, as some types are wouldn't work at all for that. For example, consider a rational number type where the denominator can get arbitrarily large: the set of positive values of that type has no least element.

I think in an ideal world the codomain of `degree` would be an arbitrarily large integer type, although I'm not sure if that's worth it because of the interop difficulties it could cause. In your case I think I would probably use `abs` and truncate - the most important thing is that a Euclidean function does exist, even if practical considerations make actually implementing it a little awkward.

**Comment by hdgarrood** [comment]
Sorry, in an ideal world it would be an arbitrarily large *natural number* type. Integers aren't well-ordered either...

**Comment by hdgarrood** [comment]
Now that I'm writing [a guide to the numeric hierarchy](https://a-guide-to-the-purescript-numeric-hierarchy.readthedocs.io/en/latest/) I think that might be a better place for this, so I'm going to close this for now.

**Comment by hdgarrood** [comment]
Anyone who would like to read more about this class should consult the chapters on the Euclidean Algorithm, polynomials, and euclidean rings in [my guide](https://a-guide-to-the-purescript-numeric-hierarchy.readthedocs.io/en/latest/euclidean-algorithm.html).
